add hyperf server

diff --git a/php-worker/Dockerfile b/php-worker/Dockerfile
--- a/php-worker/Dockerfile
+++ b/php-worker/Dockerfile
@@ -1,21 +1,96 @@
 ARG PHP_VERSION=8.3
+ARG DEBIAN_VERSION=bookworm
 
-FROM php:${PHP_VERSION}-cli-alpine
+FROM php:${PHP_VERSION}-cli-${DEBIAN_VERSION}
+
+# Set Environment Variables
+ENV DEBIAN_FRONTEND=noninteractive
 
 # Start as root
 USER root
 
-RUN apk --update add $PHPIZE_DEPS autoconf build-base linux-headers openssl-dev libmcrypt-dev openssl libxml2-dev oniguruma-dev pcre-dev zlib-dev \
-  wget bash curl \
-  libzip \
-  libzip-dev \
-  lz4-dev \
-  freetype-dev libjpeg-turbo-dev jpeg-dev libpng-dev \
-  nodejs npm supervisor \
-  && pecl channel-update pecl.php.net \
-  && pecl install -o -f -D 'enable-redis-igbinary="yes" enable-redis-lz4="yes"' igbinary redis && docker-php-ext-enable igbinary redis \
-  && docker-php-ext-configure gd --with-freetype --with-jpeg && docker-php-ext-install gd \
-  && rm -rf /tmp/pear
+RUN set -eux; \
+    apt-get update -yqq && \
+    apt-get install -yqq \
+    apt-utils \
+    curl \
+    git \
+    gnupg2 \
+    libcurl4-openssl-dev \
+    libfreetype6-dev \
+    libicu-dev \
+    libjpeg-dev \
+    liblz4-dev \
+    libmcrypt-dev \
+    libmemcached-dev \
+    libonig-dev \
+    libpng-dev \
+    libpq-dev \
+    libreadline-dev \
+    libsqlite3-dev \
+    libssl-dev \
+    libwebp-dev \
+    libxpm-dev \
+    libxml2-dev \
+    libz-dev \
+    libzip-dev \
+    nodejs \
+    npm \
+    openssl \
+    supervisor \
+    unixodbc-dev \
+    unzip \
+    zip && \
+    pecl channel-update pecl.php.net && \
+    install_php_ext() { \
+      extension="$1"; \
+      if ! php -m | grep -qi "^${extension}$"; then \
+        docker-php-ext-install -j"$(nproc)" "${extension}"; \
+      fi; \
+    }; \
+    for extension in \
+      bcmath curl dom exif fileinfo intl mbstring mysqli pcntl \
+      pdo_mysql pdo_pgsql pdo_sqlite pgsql readline simplexml sockets \
+      sysvmsg sysvsem sysvshm xml xmlreader xmlwriter zip; do \
+      install_php_ext "${extension}"; \
+    done; \
+    if ! php -m | grep -qi 'pdo_odbc'; then \
+      docker-php-ext-configure pdo_odbc --with-pdo-odbc=unixODBC,/usr && \
+      docker-php-ext-install -j"$(nproc)" pdo_odbc; \
+    fi; \
+    docker-php-ext-configure gd \
+      --prefix=/usr \
+      --with-jpeg \
+      --with-webp \
+      --with-xpm \
+      --with-freetype && \
+    docker-php-ext-install -j"$(nproc)" gd && \
+    pecl install -o -f -D 'enable-redis-igbinary="yes" enable-redis-lz4="yes"' igbinary redis && \
+    docker-php-ext-enable igbinary redis && \
+    if ! php -m | grep -qi '^msgpack$'; then \
+      pecl install msgpack && docker-php-ext-enable msgpack; \
+    fi; \
+    php -m | grep -qi 'intl' && \
+    php -m | grep -qi 'msgpack' && \
+    php -m | grep -qi 'pdo_odbc' && \
+    php -m | grep -qi 'pdo_pgsql' && \
+    php -m | grep -qi 'sockets' && \
+    php -m | grep -qi 'opcache';
+
+###########################################################################
+# PHP AHOCORASICK:
+###########################################################################
+
+ARG INSTALL_AHOCORASICK=false
+
+RUN if [ "${INSTALL_AHOCORASICK}" = true ]; then \
+    git clone --depth 1 https://git.papamk.com/packagist/aho-corasick.git /tmp/aho-corasick && \
+    cd /tmp/aho-corasick && \
+    ./build.sh && \
+    cp .libs/ahocorasick.so "$(php-config --extension-dir)/ahocorasick.so" && \
+    docker-php-ext-enable ahocorasick && \
+    php -m | grep -q '^ahocorasick$'; \
+  fi
 
 ###########################################################################
 # PHP RDKAFKA:
@@ -23,14 +98,23 @@ RUN apk --update add $PHPIZE_DEPS autoconf build-base linux-headers openssl-dev 
 ARG INSTALL_RDKAFKA=false
 
 RUN if [ ${INSTALL_RDKAFKA} = true ]; then \
-      apk add --no-cache librdkafka-dev \
+      apt-get install -yqq --no-install-recommends librdkafka-dev \
       && pecl install rdkafka \
       && docker-php-ext-enable rdkafka \
       && php -m | grep -q 'rdkafka' \
 ;fi
 
-RUN docker-php-ext-configure zip && docker-php-ext-install bcmath exif mysqli pcntl pdo_mysql zip
+###########################################################################
+# PHP SWOOLE:
+###########################################################################
+ARG INSTALL_SWOOLE=false
 
+RUN if [ ${INSTALL_SWOOLE} = true ]; then \
+      pecl install swoole \
+      && docker-php-ext-enable swoole \
+      && echo "swoole.use_shortname='Off'" > /usr/local/etc/php/conf.d/zz-swoole.ini \
+      && php -m | grep -q 'swoole' \
+;fi
 
 ###########################################################################
 # PHP GRPC:
@@ -78,10 +162,11 @@ ENV PUID=${PUID}
 ARG PGID=1000
 ENV PGID=${PGID}
 
-RUN addgroup -g ${PGID} tamadock && \
-  adduser -D -G tamadock -u ${PUID} tamadock
+RUN groupadd --gid ${PGID} tamadock && \
+  useradd --uid ${PUID} --gid ${PGID} --create-home --shell /bin/bash tamadock
 
-RUN rm /var/cache/apk/* \
+# Clean up
+RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
   && mkdir -p /var/www
 
 WORKDIR /etc/supervisor/conf.d/
